[package]
name = "simulator"
version = "0.1.0"
authors = ["James Waples <james@wapl.es>"]
edition = "2018"
default-run = "simulator"

[dependencies]
embedded-graphics = "0.7.1"
sdl2 = "0.35.2"
common = { path = "../common" }
kiss3d = "0.35.0"
embedded-graphics-simulator = "0.4.0"
